[project]
name = "pdf-extractor"
version = "0.1.0"
description = "PDF text extraction module with streaming support"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlx-vlm>=0.3.3",
    "pdfplumber>=0.11.7",
    "pillow>=11.3.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2",
]

[project.scripts]
pdf-extractor = "pdf_extractor.__main__:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = ["-v", "--tb=short"]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.13.2",
]

[tool.ruff]
# Set line length limit to 250
line-length = 250

[tool.ruff.lint]
# Select specific lint rules
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "C901", # too complex (McCabe complexity)
]

# Ignore specific rules if needed
ignore = []

# Enforce maximum file length of 250 lines
[tool.ruff.lint.pycodestyle]
max-line-length = 250

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"
# Indent with 4 spaces
indent-style = "space"
